FROM node:20-slim@sha256:securehashvalue

ENV MONGODB_CONNECTION_PROTOCOL mongodb+srv
ENV MONGODB_DB_NAME ${MONGODB_DB_NAME}
ENV MONGODB_CLUSTER_ADDRESS ${MONGODB_CLUSTER_ADDRESS}
ENV MONGODB_USERNAME ${MONGODB_USERNAME}
ENV MONGODB_PASSWORD ${MONGODB_PASSWORD}

WORKDIR /app

COPY package*.json .

RUN npm install

COPY . .

CMD ["npm", "start"]