# .github/workflows/commit.yml
name: Commit Workflow

on:
  push:
    branches:
      - '**'  # triggers on all branches

jobs:
  lint:
    name: Lint Code
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Run Linter
        run: |
          echo "Running linter..."
          npm ci
          npm run lint

  test:
    name: Run Tests
    runs-on: ubuntu-latest
    needs: lint
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Run Tests
        run: |
          echo "Running tests..."
          npm ci
          npm test

  build:
    name: Build Project
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Build Project
        run: |
          echo "Building project..."
          npm ci
          npm run build
