# .github/workflows/issues-event.yml
name: Issues Event Logger

on:
  issues:
    types: [opened, edited, closed]  # Customize as needed

jobs:
  log-issue-event:
    name: Log Issue Event Details
    runs-on: ubuntu-latest
    steps:
      - name: Output Issue Event Info
        run: |
          echo "Issue Event Triggered"
          echo "Event Name: ${{ github.event_name }}"
          echo "Action: ${{ github.event.action }}"
          echo "Repository: ${{ github.repository }}"
          echo "Issue Title: ${{ github.event.issue.title }}"
          echo "Issue Body: ${{ github.event.issue.body }}"
          echo "Issue URL: ${{ github.event.issue.html_url }}"
